### ISSUE TITLE
Frontend throwing a 500

### ISSUE THREAD

**Issue by mathcolo** [nettube/mbtapuller#51]
$ docker attach
[2016-07-31 02:46:29,649] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./main.py", line 21, in home
    lines = sorted(getAllRoutes(), key=lambda k: k['name'])
NameError: global name 'getAllRoutes' is not defined

**Comment by mathcolo** [comment]
PR #52 fixes, closing
