### ISSUE TITLE
Pull broke at 2016-08-01 12:58 UTC

### ISSUE THREAD

**Issue by mathcolo** [nettube/mbtapuller#55]
Traceback (most recent call last):
  File "./pull_data.py", line 32, in <module>
    pull(session, once=args.once)
  File "./pull_data.py", line 20, in pull
    APIFunctions.sync_trips_and_records(routes, session)
  File "/usr/src/app/APIFunctions.py", line 105, in sync_trips_and_records
    mode = data['mode']
KeyError: 'mode'

**Comment by mathcolo** [comment]
PR #56 Fix committed
